//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuneralHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public int Type { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
    }
}
